ELECTRICITY_DAILY_PRODUCTION_PER_WORKER = 3
ELECTRICITY_PRODUCTION_DAMAGE = 4
FOOD_DAILY_PRODUCTION_PER_WORKER = 5
FOOD_PRODUCTION_DAMAGE = 2
WATER_DAILY_PRODUCTION_PER_WORKER = 5
WATER_PRODUCTION_DAMAGE = 3
PRODUCTION_SHUTDOWN_THRESHOLD = 10   # (percentage)